/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ProdutoControler;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.entidades.Produto;

/**
 *
 * @author jonasidney
 */
public class FormBuscaProduto extends javax.swing.JFrame {
    
    private ProdutoControler produtoControler = new ProdutoControler();
    private FormCadProduto parent;
    private Integer idSelecionado;

    public Integer getIdSelecionado() {
        return idSelecionado;
    }
    /**
     * Creates new form FormBuscaProduto
     */
    public FormBuscaProduto(FormCadProduto parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfPesquisaProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPesquisaProduto = new javax.swing.JTable();
        jbtnPesquisaProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pesquisar:");

        jtfPesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaProdutoKeyPressed(evt);
            }
        });

        jtbPesquisaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descricao", "Preço", "Unidade", "Tipo", "Status", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbPesquisaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPesquisaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPesquisaProduto);

        jbtnPesquisaProduto.setText("Selecionar");
        jbtnPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesquisaProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtnPesquisaProduto)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaProdutoKeyPressed
        if (jtfPesquisaProduto.getText() != null && jtfPesquisaProduto.getText().length() > 3){
            System.out.println("teste"+jtfPesquisaProduto.getText());
            
            ArrayList<Produto> pesquisaProdutoPorTexto = produtoControler.pesquisaPorTexto(jtfPesquisaProduto.getText());
            if (pesquisaProdutoPorTexto != null && !pesquisaProdutoPorTexto.isEmpty()){
                DefaultTableModel model = (DefaultTableModel) jtbPesquisaProduto.getModel();
                model.setNumRows(0);
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                for (Produto produto : pesquisaProdutoPorTexto) {
                    model.addRow(new Object[]{
                        produto.getId(),
                        produto.getNome(),
                        produto.getDescricao(),
                        produto.getPreco_unitario(),
                        produto.getUnidade(),
                        produto.getTipoproduto(),
                        produto.isRegistro_ativo(),
                        sdf.format(produto.getDataRegistro())
                    });
                }
            }
        }    
    }//GEN-LAST:event_jtfPesquisaProdutoKeyPressed

    private void jbtnPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesquisaProdutoActionPerformed
        // TODO add your handling code here:
        parent.preencherProdutoSelecionado(idSelecionado);
        this.dispose();
    }//GEN-LAST:event_jbtnPesquisaProdutoActionPerformed

    private void jtbPesquisaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPesquisaProdutoMouseClicked
        // TODO add your handling code here:
        if (jtbPesquisaProduto.getSelectedRow() != -1){
            idSelecionado = (Integer) jtbPesquisaProduto.getValueAt(jtbPesquisaProduto.getSelectedRow(), 0);
        }
    }//GEN-LAST:event_jtbPesquisaProdutoMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPesquisaProduto;
    private javax.swing.JTable jtbPesquisaProduto;
    private javax.swing.JTextField jtfPesquisaProduto;
    // End of variables declaration//GEN-END:variables
}
